server :
  port : 6001
  servlet.context-path : /springboot

spring:
  profiles.active: "@profileActive@"
  application:
    name: server

  cloud:
    service-registry:
      auto-registration:
        enabled: false

  rabbitmq:
    addresses: 8.142.46.67:5672
    username: hz
    password: hz15858
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


  resources.static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://8.142.46.67:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&autoReconnect=true&failOverReadOnly=false&useSSL=false
    #driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: hz15858
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

  redis:
    port: 6379
    host: 8.142.46.67
    database: 0
    password: hz15858


  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: kuwvhzyxkknujigi
    username: 1102211390@qq.com
    port: 587
    properties:
      mail:
        stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true

#  thymeleaf:
#    prefix: classpath:/templates/
#    mode: HTML
#    cache: false
#    encoding: UTF-8
#    #     新版本不支持content-type: text/html，故新写法
#    servlet:
#      content-type: text/html

mybatis :
  mapper-locations: classpath:/com/hz/mapper/*.xml
  type-aliases-package: com.hz.demo.entity
  #配置驼峰
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

#logging:
#  level:
#    root: info
#    com.hz.dao: debug
#
#    eureka.client.healthcheck.enabled: false


#  file:
#    name: E:\springboot.log



# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:6890/eureka/
      defaultZone: http://user:password@localhost:6890/eureka
  instance:
    instance-id: server-8080
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    hostname: ${spring.application.name}


aliyun:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  urlPrefix:

