server:
  port: 9101

spring:
  application:
    name: gateway9101

  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 8.142.46.67:8848

    gateway:
      discovery: #配置网关发现机制
        locator: #配置处理机制
          # 只要请求地址符合规则： http://gatewayIP:gatewayPort/微服务名称/微服务请求地址
          # 网关自动映射、把请求转发到http://微服务名称/微服务请求地址
          # 如: 有微服务，命名是ribbon-app-service
          # 请求地址是: 例如
          # 商业开发中，enable一般不设置，使用默认值false。避免不必要的自动转发规则。
          enabled: false #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      #路由
      routes:
        - id: gateway8001    #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment
          predicates: #配置谓词集合
            - Path=/payment/getPaymentById/** #断言，路径相匹配的进行路由
            - After=2021-11-29T11:15:12.466+08:00[Asia/Shanghai]

management:
  endpoints:
    web:
      exposure:
        include: '*'


