spring:
  application:
    name: grpc-server

  redis:
    #    cluster:
    #      nodes:
    #        -
    # Redis服务器连接端口
    port: 6379
    # Redis服务器地址
    host: 8.142.46.67
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码
    password: hz15858
    # 连接超时时间（毫秒）
    timeout: 1000
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1

grpc:
  server:
    port: 7052

server:
  port: 9002