server:
  port: 8803

spring:
  application:
    name: stream-rabbitmq-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                addresses: 8.142.46.67
                port: 5672
                username: hz
                password: hz15858
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          defaultbinder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: consumer1 #设置是否同组 不同组会造成重复消费

eureka:
  #  instance:
  #    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:6890/eureka/
      defaultZone: http://user:password@localhost:6890/eureka
    healthcheck:
      enabled: true

  instance:
    instance-id: stream-rabbitmq-consumer8803
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include=*,hystrix:
          stream:

info:
  app.name: eureka
  company:
    name: hz
  build:
    artifactId: "@project.artifactId@"
    version: "@project.version@"

