server:
  port: 3344
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:h-ze/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:6890/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: config-center-3344
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2