server :
  port : 8101
  #servlet.context-path : /eurekaconsumer

spring:
  application:
    name: openFeignProvider
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

#  data:
#    mongodb:
#      database: admin
#      host: 127.0.0.1
#      password:
#      port: 27017
#      username:

eureka:
#  instance:
#    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:6890/eureka/
      defaultZone: http://user:password@localhost:6890/eureka
    healthcheck:
      enabled: true

  instance:
    instance-id: openFeignProvider-8101
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include=*,hystrix:
          stream:

info:
  app.name: eureka
  company:
    name: hz
  build:
    artifactId: "@project.artifactId@"
    version: "@project.version@"

feign:
  hystrix:
    enabled: true
