server:
  port: 8401
#  servlet:
#    context-path: provider-payment

spring:
  #profiles.active: "@profileActive@"
  application:
    name: cloudAlibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: 8.142.46.67:8848
        #server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        #端口号默认为8719
        port: 8719

      datasource:
        ds1:
          nacos:
            server-addr: 8.142.46.67:8848
            dataId: cloudAlibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

#  redis:
#    port: 6379
#    host: localhost
#    database: 0




logging:
  level:
    root: info
    com.hz.dao: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
