nacos:
  # Nacos的地址
  server-addr: @service.nacos.host@
  server-port: @service.nacos.port@
  name: @service.nacos.username@
  password: @service.nacos.password@
  # Nacos的命名空间
  #namespace: 37bbdab4-de3f-4c07-927a-7b0fdb66348e
  namespace: @service.nacos.namespace@
  # Nacos的配置分组
  group: @service.group@
  # Seata Server的配置
  seata:
    application: @service.seata.application@
    tx-service-group: @service.seata.tx-service-group@

mysql:
  user: @service.mysql.user@
  pwd: @service.mysql.password@

rbt:
  user: @service.rabbit.user@
  psd: @service.rabbit.password@
  port: @service.rabbit.port@
  addr: @service.rabbit.address@

rds:
  port: @service.redis.port@
  host: @service.redis.address@
  password: @service.redis.password@
  database: @service.redis.database@

server:
  port: 9101

spring:
  application:
    name: gateway9101

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8888/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: ${rds.database}
    port: ${rds.port}
    host: ${rds.host}
    password: ${rds.password}

  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        port: ${nacos.server-port}
    gateway:
      discovery: #配置网关发现机制
        locator: #配置处理机制
          # 只要请求地址符合规则： http://gatewayIP:gatewayPort/微服务名称/微服务请求地址
          # 网关自动映射、把请求转发到http://微服务名称/微服务请求地址
          # 如: 有微服务，命名是ribbon-app-service
          # 请求地址是: 例如
          # 商业开发中，enable一般不设置，使用默认值false。避免不必要的自动转发规则。
          enabled: false #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      #路由
      routes:
        - id: gateway8001    #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloudAlibaba-provider-payment
          predicates: #配置谓词集合
            - Path=/payment/** #断言，路径相匹配的进行路由
            - After=2021-11-29T11:15:12.466+08:00[Asia/Shanghai]

        - id: auth
          uri: lb://auth
          predicates: #配置谓词集合
            - Path=/** #断言，路径相匹配的进行路由
            - After=2021-11-29T11:15:12.466+08:00[Asia/Shanghai]

        - id: order9999
          uri: lb://cloudAlibaba-order-service
          predicates:
            - Path=/order/**
            - After=2021-11-29T11:15:12.466+08:00[Asia/Shanghai]

        - id: cloudAlibaba-seata-order-service
          uri: lb://cloudAlibaba-seata-order-service
          predicates:
            - Path=/order/**
            - After=2021-11-29T11:15:12.466+08:00[Asia/Shanghai]

management:
  endpoints:
    web:
      exposure:
        include: '*'

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/oauth/token"

