spring:
  redis:
    #spring boot初始化redisTemplate需要用到nodes这个字段，初始化RedisSentineManager需要用到host这个字段
    sentinel:
      master: mymaster
      nodes: 124.223.191.89:26379,8.142.46.67:26379,114.55.119.114:26379
      host: 124.223.191.89:26379,8.142.46.67:26379,114.55.119.114:26379
      password: hz15858

    #cluster:
    #  nodes: 124.223.191.89:6379,8.142.46.67:6379,114.55.119.114:6379
    #  max-redirects: 3
    #    cluster:
    #      nodes:
    #        -
    # Redis服务器连接端口
    #port: 6379
    # Redis服务器地址
    #host: 8.142.46.67
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码
    password: hz15858
    # 连接超时时间（毫秒）
    timeout: 1000
    # 连接池最大连接数（使用负值表示没有限制）
    #lettuce:
    jedis:

      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1