server:
  port: 84
#  servlet:
#    context-path: provider-payment

spring:
  #profiles.active: "@profileActive@"
  application:
    name: cloudAlibaba-sentinel-order
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 8.142.46.67:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        #端口号默认为8719
        port: 8719
#  rabbitmq:
#    addresses: 127.0.0.1:5672
#    username: guest
#    password: guest
#    virtual-host: /
#    publisher-confirms: true
#    publisher-returns: true
#    template:
#      mandatory: true


  resources.static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

#  redis:
#    port: 6379
#    host: localhost
#    database: 0


mybatis :
  mapper-locations: classpath:/com/payment/mapper/*.xml
  type-aliases-package: com.hz.demo.entity

logging:
  level:
    root: info
    com.hz.dao: debug

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
