// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package hz.lib;

public interface booleanReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.booleanReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool reply = 1;</code>
   */
  boolean getReply();
}
