// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package hz.lib;

public final class DeviceFixProto {
  private DeviceFixProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_conditionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_conditionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_deviceFix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_deviceFix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_booleanReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_booleanReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_objectReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_objectReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013hello.proto\022\006device\"\037\n\021conditionsReque" +
      "st\022\n\n\002id\030\001 \001(\t\"\222\001\n\tdeviceFix\022\n\n\002id\030\001 \001(\t" +
      "\022\021\n\tserialNum\030\002 \001(\t\022\017\n\007userNum\030\003 \001(\t\022\016\n\006" +
      "status\030\004 \001(\005\022\014\n\004type\030\005 \001(\005\022\017\n\007address\030\006 " +
      "\001(\t\022\022\n\ncreatetime\030\007 \001(\t\022\022\n\nupdatetime\030\010 " +
      "\001(\t\"\035\n\014booleanReply\022\r\n\005reply\030\001 \001(\010\"\034\n\013ob" +
      "jectReply\022\r\n\005reply\030\001 \001(\0102\227\002\n\020DeviceFixSe" +
      "rvice\022<\n\017insertDeviceFix\022\021.device.device" +
      "Fix\032\024.device.booleanReply\"\000\022<\n\017updateDev" +
      "iceFix\022\021.device.deviceFix\032\024.device.boole",
      "anReply\"\000\022A\n\017searchDeviceFix\022\031.device.co" +
      "nditionsRequest\032\021.device.deviceFix\"\000\022D\n\017" +
      "deleteDeviceFix\022\031.device.conditionsReque" +
      "st\032\024.device.booleanReply\"\000B4\n\032com.aiccms" +
      ".device.grpc.libB\016DeviceFixProtoP\001\242\002\003HLW" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_device_conditionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_device_conditionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_conditionsRequest_descriptor,
        new String[] { "Id", });
    internal_static_device_deviceFix_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_device_deviceFix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_deviceFix_descriptor,
        new String[] { "Id", "SerialNum", "UserNum", "Status", "Type", "Address", "Createtime", "Updatetime", });
    internal_static_device_booleanReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_device_booleanReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_booleanReply_descriptor,
        new String[] { "Reply", });
    internal_static_device_objectReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_device_objectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_objectReply_descriptor,
        new String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
