// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package hz.lib;

public interface deviceFixOrBuilder extends
    // @@protoc_insertion_point(interface_extends:device.deviceFix)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string serialNum = 2;</code>
   */
  String getSerialNum();
  /**
   * <code>string serialNum = 2;</code>
   */
  com.google.protobuf.ByteString
      getSerialNumBytes();

  /**
   * <code>string userNum = 3;</code>
   */
  String getUserNum();
  /**
   * <code>string userNum = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserNumBytes();

  /**
   * <code>int32 status = 4;</code>
   */
  int getStatus();

  /**
   * <code>int32 type = 5;</code>
   */
  int getType();

  /**
   * <code>string address = 6;</code>
   */
  String getAddress();
  /**
   * <code>string address = 6;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string createtime = 7;</code>
   */
  String getCreatetime();
  /**
   * <code>string createtime = 7;</code>
   */
  com.google.protobuf.ByteString
      getCreatetimeBytes();

  /**
   * <code>string updatetime = 8;</code>
   */
  String getUpdatetime();
  /**
   * <code>string updatetime = 8;</code>
   */
  com.google.protobuf.ByteString
      getUpdatetimeBytes();
}
