server:
  port: 9100

spring:
  application:
    name: gateway9100

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由

      routes:
        - id: gateway8001    #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/getPaymentById/** #断言，路径相匹配的进行路由
            - After=2021-11-29T11:15:12.466+08:00[Asia/Shanghai]
eureka:
  #  instance:
  #    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:6890/eureka/
      defaultZone: http://user:password@localhost:6890/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: gateway-9100
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


