server:
  port: 9100

spring:
  application:
    name: gateway9100

  cloud:
    gateway:
      routes:
        - id: gateway8001    #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/** #断言，路径相匹配的进行路由

eureka:
  #  instance:
  #    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:6890/eureka/
      defaultZone: http://user:password@localhost:6890/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: eurekaconsumer-8087
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


